/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef DATABASEFILENAME_H
#define DATABASEFILENAME_H

/*
 * function declarations 
 */
void            init_databasefilename(void);
Netsnmp_Node_Handler handle_databasefilename;

#endif                          /* DATABASEFILENAME_H */
/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef IP_H
#define IP_H

/*
 * function declarations 
 */
void            init_ip(void);
Netsnmp_Node_Handler handle_ip;

#endif                          /* IP_H */
/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef PORT_H
#define PORT_H

/*
 * function declarations 
 */
void            init_port(void);
Netsnmp_Node_Handler handle_port;

#endif                          /* PORT_H */
/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef STARTTIME_H
#define STARTTIME_H

/*
 * function declarations 
 */
void            init_starttime(void);
Netsnmp_Node_Handler handle_starttime;

#endif                          /* STARTTIME_H */
/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef REQUESTSPERHOUR_H
#define REQUESTSPERHOUR_H

/*
 * function declarations 
 */
void            init_requestsperhour(void);
Netsnmp_Node_Handler handle_requestsperhour;

#endif                          /* REQUESTSPERHOUR_H */
/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef LASTMAC_H
#define LASTMAC_H

/*
 * function declarations 
 */
void            init_lastmac(void);
Netsnmp_Node_Handler handle_lastmac;

#endif                          /* LASTMAC_H */
/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef LASTSSISIGNAL_H
#define LASTSSISIGNAL_H

/*
 * function declarations 
 */
void            init_lastssisignal(void);
Netsnmp_Node_Handler handle_lastssisignal;

#endif                          /* LASTSSISIGNAL_H */
/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef TOTALMAC_H
#define TOTALMAC_H

/*
 * function declarations 
 */
void            init_totalmac(void);
Netsnmp_Node_Handler handle_totalmac;

#endif                          /* TOTALMAC_H */
/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef DATABASEFILESIZE_H
#define DATABASEFILESIZE_H

/*
 * function declarations 
 */
void            init_databasefilesize(void);
Netsnmp_Node_Handler handle_databasefilesize;

#endif                          /* DATABASEFILESIZE_H */
/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef MEMORYPEAK_H
#define MEMORYPEAK_H

/*
 * function declarations 
 */
void            init_memorypeak(void);
Netsnmp_Node_Handler handle_memorypeak;

#endif                          /* MEMORYPEAK_H */
/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef MEMORYCURRENT_H
#define MEMORYCURRENT_H

/*
 * function declarations 
 */
void            init_memorycurrent(void);
Netsnmp_Node_Handler handle_memorycurrent;

#endif                          /* MEMORYCURRENT_H */
/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef ERRORCOUNT_H
#define ERRORCOUNT_H

/*
 * function declarations 
 */
void            init_errorcount(void);
Netsnmp_Node_Handler handle_errorcount;

#endif                          /* ERRORCOUNT_H */
